version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget_manager_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_DB_URI=mongodb://mongo:27017/budget_manager
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - kafka

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  kafka:
    image: bitnami/kafka:3
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092" # Internal communication
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: zookeeper
    ports:
      - "2181:2181"

volumes:
  mongo-data:
